require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RankingsController do

  # This should return the minimal set of attributes required to create a valid
  # Ranking. As you add validations to Ranking, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "data" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RankingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rankings as @rankings" do
      ranking = Ranking.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rankings).should eq([ranking])
    end
  end

  describe "GET show" do
    it "assigns the requested ranking as @ranking" do
      ranking = Ranking.create! valid_attributes
      get :show, {:id => ranking.to_param}, valid_session
      assigns(:ranking).should eq(ranking)
    end
  end

  describe "GET new" do
    it "assigns a new ranking as @ranking" do
      get :new, {}, valid_session
      assigns(:ranking).should be_a_new(Ranking)
    end
  end

  describe "GET edit" do
    it "assigns the requested ranking as @ranking" do
      ranking = Ranking.create! valid_attributes
      get :edit, {:id => ranking.to_param}, valid_session
      assigns(:ranking).should eq(ranking)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ranking" do
        expect {
          post :create, {:ranking => valid_attributes}, valid_session
        }.to change(Ranking, :count).by(1)
      end

      it "assigns a newly created ranking as @ranking" do
        post :create, {:ranking => valid_attributes}, valid_session
        assigns(:ranking).should be_a(Ranking)
        assigns(:ranking).should be_persisted
      end

      it "redirects to the created ranking" do
        post :create, {:ranking => valid_attributes}, valid_session
        response.should redirect_to(Ranking.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ranking as @ranking" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ranking.any_instance.stub(:save).and_return(false)
        post :create, {:ranking => { "data" => "invalid value" }}, valid_session
        assigns(:ranking).should be_a_new(Ranking)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ranking.any_instance.stub(:save).and_return(false)
        post :create, {:ranking => { "data" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ranking" do
        ranking = Ranking.create! valid_attributes
        # Assuming there are no other rankings in the database, this
        # specifies that the Ranking created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ranking.any_instance.should_receive(:update_attributes).with({ "data" => "" })
        put :update, {:id => ranking.to_param, :ranking => { "data" => "" }}, valid_session
      end

      it "assigns the requested ranking as @ranking" do
        ranking = Ranking.create! valid_attributes
        put :update, {:id => ranking.to_param, :ranking => valid_attributes}, valid_session
        assigns(:ranking).should eq(ranking)
      end

      it "redirects to the ranking" do
        ranking = Ranking.create! valid_attributes
        put :update, {:id => ranking.to_param, :ranking => valid_attributes}, valid_session
        response.should redirect_to(ranking)
      end
    end

    describe "with invalid params" do
      it "assigns the ranking as @ranking" do
        ranking = Ranking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ranking.any_instance.stub(:save).and_return(false)
        put :update, {:id => ranking.to_param, :ranking => { "data" => "invalid value" }}, valid_session
        assigns(:ranking).should eq(ranking)
      end

      it "re-renders the 'edit' template" do
        ranking = Ranking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ranking.any_instance.stub(:save).and_return(false)
        put :update, {:id => ranking.to_param, :ranking => { "data" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ranking" do
      ranking = Ranking.create! valid_attributes
      expect {
        delete :destroy, {:id => ranking.to_param}, valid_session
      }.to change(Ranking, :count).by(-1)
    end

    it "redirects to the rankings list" do
      ranking = Ranking.create! valid_attributes
      delete :destroy, {:id => ranking.to_param}, valid_session
      response.should redirect_to(rankings_url)
    end
  end

end
